# The master password is generated by Terraform and never written to the repo.
# NOTE: it is stored in the Terraform state, so keep state in an encrypted backend.
resource "random_password" "db_master" {
  length  = 24
  special = true
  # RDS MySQL rejects '/', '@', '"' and spaces in passwords.
  override_special = "!#$%^&*()-_=+[]<>:?"
}

resource "aws_secretsmanager_secret" "db_credentials" {
  name                    = var.secret_name
  description             = "Credentials for the document metadata database (read by the document-management Lambda function)"
  recovery_window_in_days = var.secret_recovery_window_days

  tags = {
    Name = var.secret_name
  }
}

resource "aws_secretsmanager_secret_version" "db_credentials" {
  secret_id = aws_secretsmanager_secret.db_credentials.id

  secret_string = jsonencode({
    username = var.db_username
    password = random_password.db_master.result
    host     = aws_db_instance.metadata.address
    port     = aws_db_instance.metadata.port
    dbname   = var.db_name
  })
}
